# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: true
  rewritePath: true
  pathPrefix: "/hello-world"
  # enabled: true
  # className: nginx
  #   annotations:
  #   # Reference: https://kubernetes.github.io/ingress-nginx/examples/rewrite/
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /hello-world(/|$)(.*)
  #         pathType: ImplementationSpecific  
service:
  # type: LoadBalancer
  type: ClusterIP
  port: 80

deployment:
  replicaCount: 2
  container:
    image:
      repository: "paulbouwer/hello-kubernetes"
      tag: "" # uses chart appVersion if not provided
      pullPolicy: IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}
