# Provide a custom message
message: "Hello World"

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: true
  rewritePath: true
  pathPrefix: "hello-world" 

service:
  type: ClusterIP
  port: 80

deployment:
  replicaCount: 2
  container:
    image:
      repository: "crazytechie1990/nextgenhubdemo"
      tag: "" # uses chart appVersion if not provided
      pullPolicy: IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

